apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dotnet-calc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dotnet-calc
    spec:
      containers:
      - name: dotnet-calc
        image: eu.gcr.io/burnished-fold-149817/dotnet-calc:v2
        ports:
        - containerPort: 5000
