apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dotnet-calc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dotnet-calc
    spec:
      containers:
      - name: dotnet-calc
        image: sjostric/calc-app:1.0.0-SNAPSHOT
        ports:
        - containerPort: 5000
